// Generated by jextract

package io.crowds.lib.boringtun;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final VarHandle const$0 = constants$0.const$3.varHandle(PathElement.groupElement("rx_bytes"));
    static final VarHandle const$1 = constants$0.const$3.varHandle(PathElement.groupElement("estimated_loss"));
    static final VarHandle const$2 = constants$0.const$3.varHandle(PathElement.groupElement("estimated_rtt"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(set_logging_function$log_func.class, "apply", constants$1.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$1.const$3
    );
}


