// Generated by jextract

package io.crowds.lib.boringtun;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("op"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("size")
    ).withName("wireguard_result");
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("op"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("size"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_LONG.withName("time_since_last_handshake"),
        JAVA_LONG.withName("tx_bytes"),
        JAVA_LONG.withName("rx_bytes"),
        JAVA_FLOAT.withName("estimated_loss"),
        JAVA_INT.withName("estimated_rtt"),
        MemoryLayout.sequenceLayout(56, JAVA_BYTE).withName("reserved")
    ).withName("stats");
    static final VarHandle const$4 = constants$0.const$3.varHandle(PathElement.groupElement("time_since_last_handshake"));
    static final VarHandle const$5 = constants$0.const$3.varHandle(PathElement.groupElement("tx_bytes"));
}


