// Generated by jextract

package io.crowds.lib.boringtun;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;

class constants$1 {

    static final FunctionDescriptor x25519_public_key$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(32, Constants$root.C_CHAR$LAYOUT).withName("key")
    ).withName("x25519_key"),
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(32, Constants$root.C_CHAR$LAYOUT).withName("key")
        ).withName("x25519_key")
    );
    static final MethodHandle x25519_public_key$MH = RuntimeHelper.downcallHandle(
        "x25519_public_key",
        constants$1.x25519_public_key$FUNC
    );
    static final FunctionDescriptor x25519_key_to_base64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(32, Constants$root.C_CHAR$LAYOUT).withName("key")
        ).withName("x25519_key")
    );
    static final MethodHandle x25519_key_to_base64$MH = RuntimeHelper.downcallHandle(
        "x25519_key_to_base64",
        constants$1.x25519_key_to_base64$FUNC
    );
    static final FunctionDescriptor x25519_key_to_hex$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(32, Constants$root.C_CHAR$LAYOUT).withName("key")
        ).withName("x25519_key")
    );
    static final MethodHandle x25519_key_to_hex$MH = RuntimeHelper.downcallHandle(
        "x25519_key_to_hex",
        constants$1.x25519_key_to_hex$FUNC
    );
    static final FunctionDescriptor x25519_key_to_str_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle x25519_key_to_str_free$MH = RuntimeHelper.downcallHandle(
        "x25519_key_to_str_free",
        constants$1.x25519_key_to_str_free$FUNC
    );
    static final FunctionDescriptor check_base64_encoded_x25519_key$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle check_base64_encoded_x25519_key$MH = RuntimeHelper.downcallHandle(
        "check_base64_encoded_x25519_key",
        constants$1.check_base64_encoded_x25519_key$FUNC
    );
    static final FunctionDescriptor new_tunnel$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle new_tunnel$MH = RuntimeHelper.downcallHandle(
        "new_tunnel",
        constants$1.new_tunnel$FUNC
    );
}


