// Generated by jextract

package io.crowds.lib.boringtun;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*set_logging_function$log_func)(char*);
 * }
 */
public interface set_logging_function$log_func {

    void apply(MemorySegment _x0);
    static MemorySegment allocate(set_logging_function$log_func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$1.const$4, fi, constants$1.const$3, scope);
    }
    static set_logging_function$log_func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment __x0) -> {
            try {
                constants$1.const$5.invokeExact(symbol, __x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


